### ISSUE TITLE
Specify chunking in `read_data`

### ISSUE THREAD

**Issue by seamanticscience** [jbusecke/cmip6_preprocessing#1]
I would like to adjust the chunking of CMIP6 data read in using `read_data` for `Dask` calculations. Specify as an input like `intake-esm`?

**Comment by jbusecke** [comment]
I can implememt
that soonish. However it might become obsolete once `intake-esm` fully supports a `preprocessing` function [here](https://github.com/NCAR/intake-esm/pull/155). Let me
know if you need this urgently otherwise I am inclined to wait for a more substantial refactor.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by seamanticscience** [comment]
Ok thanks, I can just carry on using  the `chunk` method where needed.

**Comment by jbusecke** [comment]
I think this is outdated in the released version, correct? Closing
