### ISSUE TITLE
Better structure for different 'levels' of preprocessing.

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#95]
I have been thinking about a major restructuring of the package which would go along with an actual documentation. 

This has been inspired by the continued use of the package in my own projects and some great discussions in the Pangeo CMIP6 group. In particular @agstephens got me thinking about what cmip6_preprocessing 'fixes' at which 'level' of the processing.

Let me try to illustrate:

- All CMIP6 data starts from multiple `files`.

- These files then form a `dataset` (this is usually a single variable)

- Several datasets of different variables and grid metrics can be combined to a `member`, which represents 'the stuff you would normally get when you run a model', e.g. a bunch of variables (possibly on a staggered grid) and maybe some grid metrics like the vertical cell thickness and cell area.

- Then some models have several members, which can be combined again, calling this an `experiment` (e.g. a preindustrial control experiment, or a historical forcing experiment).

- One could then combine these experiments into some sort of super dataset for each model, but that is often impractical due to the different time frames they run over, so ill stop here.

Or in short for each level `file`-`dataset`-`member`-`experiment`.

It is important to know when a `fix` should/has to be applied. There are many fixes that have been applied by @naomi-henderson on the `file` level in order to put out the zarr stores for the [Pangeo CMIP6 data](https://pangeo-data.github.io/pangeo-cmip6-cloud/accessing_data.html#preprocessing-the-cmip6-datasets). 

Most of the stuff in the `preprocessing.py` module is meant to be applied at the `dataset` level, but I am planning to add more of my prototyped code to the package soon and so I wanted to discuss if everybody thinks that this 'vocabulary' looks ok or if I am missing some important level/use-case here.

**Comment by dcherian** [comment]
See https://daops.readthedocs.io/en/latest/readme.html for ideas?

**Comment by agstephens** [comment]
@jbusecke I think your file/dataset/member/experiment approach makes sense for most use cases. I tend to think of CMIP6 as a multi-dimensional hypercube of facets, e.g. MIP, Institute, Model, Experiment, EnsembleMember etc.

I think that there are some _slices_ through the hypercube that will not be covered by your approach. An extension over multiple experiments that can be logically aggregated. Because of that, we wanted to generalise our approach in `daops` so that everything was reduced to a simple dataset ID string. This has its pros and cons. The main pro is that it avoids the software knowing about any complex hierarchies and relationships. The main con is that you need one "fix" record per ESGF Dataset - which means you need a big data store to hold them. I'm still not sure what the best approach is. 

(Part of me has been thinking a lot about STAC/Intake/Xarray/others in terms of aggregations and hierarchies...in some cases, there is value in recording information at the granular (e.g. file) level and in others it is much more useful/efficient to look at higher order aggregations - unfortunately, we seem to need both at the same time...and the ultimate software will transition between them seamlessly).

**Comment by jbusecke** [comment]
Thanks for the input @agstephens, indeed I myself have been switching back and forth between processing a full experiment and single members. I think ultimately I favor the more fine-grained approach here, purely for computational reasons related to xarray/dask (they regularly blow up in my processing pipeline, even with just a single member). 

I think as a short-term goal I will try to migrate some of my more fine-grained fixes to the `daops` framework to get acquainted with it and then we should see how to migrate the other features. That will take some time since my current approach is rather 'check and process if necessary' for every dataset, whereas with a `daops` based approach this would be separated into a `scan and parse` step or manual entry that is carried out before the datasets are actually modified, if I understand correctly.

Let me actually start with some easy metadata corrections. Ill start an issue over at daops for that.

**Comment by jbusecke** [comment]
I have added a modified version of this graph and some text in the [docs](https://cmip6-preprocessing.readthedocs.io/en/latest/#suggested-workflow). I will close this issue for now.
